package com.nenton.speechya.data.storage.models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nenton.speechya.data.storage.models.Dialog;
import com.nenton.speechya.data.storage.models.Messages;
import com.nenton.speechya.data.storage.models.StandartPhrase;

import com.nenton.speechya.data.storage.models.DialogDao;
import com.nenton.speechya.data.storage.models.MessagesDao;
import com.nenton.speechya.data.storage.models.StandartPhraseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dialogDaoConfig;
    private final DaoConfig messagesDaoConfig;
    private final DaoConfig standartPhraseDaoConfig;

    private final DialogDao dialogDao;
    private final MessagesDao messagesDao;
    private final StandartPhraseDao standartPhraseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dialogDaoConfig = daoConfigMap.get(DialogDao.class).clone();
        dialogDaoConfig.initIdentityScope(type);

        messagesDaoConfig = daoConfigMap.get(MessagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        standartPhraseDaoConfig = daoConfigMap.get(StandartPhraseDao.class).clone();
        standartPhraseDaoConfig.initIdentityScope(type);

        dialogDao = new DialogDao(dialogDaoConfig, this);
        messagesDao = new MessagesDao(messagesDaoConfig, this);
        standartPhraseDao = new StandartPhraseDao(standartPhraseDaoConfig, this);

        registerDao(Dialog.class, dialogDao);
        registerDao(Messages.class, messagesDao);
        registerDao(StandartPhrase.class, standartPhraseDao);
    }
    
    public void clear() {
        dialogDaoConfig.getIdentityScope().clear();
        messagesDaoConfig.getIdentityScope().clear();
        standartPhraseDaoConfig.getIdentityScope().clear();
    }

    public DialogDao getDialogDao() {
        return dialogDao;
    }

    public MessagesDao getMessagesDao() {
        return messagesDao;
    }

    public StandartPhraseDao getStandartPhraseDao() {
        return standartPhraseDao;
    }

}
